name: 'repo2docker Action'
description: 'Creates a docker image of your repository to view the collection of notebooks'
inputs:
  DOCKER_USERNAME:
    description: Docker registry username
    require: true
  DOCKER_PASSWORD:
    description: Docker registry password
    required: true
  DOCKER_REGISTRY:
    description: name of the docker registry.  If not supplied, this defaults to registry.hub.docker.com.
    require: false
  IMAGE_NAME:
    description: name of the image.  Example - myusername/myContainer.  If not supplied, this defaults to $DOCKER_USERNAME/$GITHUB_REPOSITORY_NAME
    require: false
  NOTEBOOK_USER:
    description: username of the primary user in the image
    require: false
outputs:
  IMAGE_SHA_NAME:
    description: The name of the docker image, which is tagged with the SHA.
runs:
  using: 'docker'
  image: 'Dockerfile'
