name: 'repo2docker Action'
description: 'Creates a docker image of your repository to view the collection of notebooks'
inputs:
  DOCKER_USERNAME:
    description: Docker registry username
    require: true
  DOCKER_PASSWORD:
    description: Docker registry password
    required: true
  DOCKER_REGISTRY:
    description: name of the docker registry.  If not supplied, this defaults to registry.hub.docker.com.
    require: false
  IMAGE_NAME:
    description: name of the image.  Example - myusername/myContainer.  If not supplied, this defaults to $DOCKER_USERNAME/$GITHUB_REPOSITORY_NAME
    require: false
  NOTEBOOK_USER:
    description: username of the primary user in the image
    require: false
  LATEST_TAG_OFF:
    description: Setting this variable to any value will prevent your image from being tagged with `latest`, in additiona to the GitHub commit SHA.  This is enabled by default.
    require: false
  ADDITIONAL_TAG:
    description: An optional string that specifies the name of an additional tag you would like to apply to the image.  Images are already tagged with the relevant GitHub SHA.
    require: false
  DEBUG:
    description: Setting this variable to any value will turn debug mode on.  When debug mode is on, images will not be pushed to the registry.  Furthermore, verbose logging will be enabled.
    require: false
outputs:
  IMAGE_SHA_NAME:
    description: The name of the docker image, which is tagged with the SHA.
runs:
  using: 'docker'
  image: 'Dockerfile'
