name: CI
on: push

jobs:
  Test-Action:
    runs-on: ubuntu-latest
    steps:
    - name: see payload
      run: | 
        echo $PAYLOAD
        echo $REF
      env:
        PAYLOAD: ${{ github.event }}
        REF: ${{ github.event.ref }}

    - name: cache binder build on mybinder.org
      uses: machine-learning-apps/repo2docker-action@0.2
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }}
