name: Test
on: [pull_request]

jobs:    
  test-registry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_name: ['repo2docker-test', '']
        tag: ['test-tag', '']
        no_push: [true, '']
        latest_off: [true, '']
    services:
      local-registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:  
    - name: Checkout
      uses: actions/checkout@v2
    - name: test action
      uses: ./
      with:
        IMAGE_NAME: ${{ matrix.image_name }}
        ADDITIONAL_TAG: ${{ matrix.tag }}
        NO_PUSH: ${{ matrix.push }}
        LATEST_TAG_OFF: ${{ matrix.latest_off }}
        DOCKER_REGISTRY: "localhost:5000"
        DOCKER_USERNAME: 'foo'
        DOCKER_PASSWORD: 'foo'

  mybinder:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout PR
      uses: actions/checkout@v2
        
    - name: mybinder
      uses: ./
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.sha }}
