name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: see var
      run: echo $BOOL
      env:
        BOOL: ${{ ! (contains(github.event.pull_request.title, '[skip-test]')) }}

    - name: checkout files in repo
      uses: actions/checkout@master

    - name: try-local-build
      uses: ./
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: "hamelsmu/repo2docker-test"

         