name: Test
on: [pull_request]

jobs:    
  imagename:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: push to dockerhub
      uses: ./
      with:
        IMAGE_NAME: "hamelsmu/repo2docker-test"
        NO_PUSH: true

  no-imagename:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout PR
      uses: actions/checkout@v2
  
    - name: push to dockerhub w/additional tag
      uses: ./
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        ADDITIONAL_TAG: 'test-additional-tag'
        NO_PUSH: true

  no-push-no-registry:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: no push
      uses: ./
      with:
        NO_PUSH: 'true'
        IMAGE_NAME: "hamelsmu/repo2docker-test"

    - name: no push without latest tag
      uses: ./
      with:
        NO_PUSH: 'true'
        LATEST_TAG_OFF: 'true'
        IMAGE_NAME: "hamelsmu/repo2docker-test"

  mybinder:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout PR
      uses: actions/checkout@v2
        
    - name: mybinder
      uses: ./
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.sha }}

