name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: try-local-build
      uses: ./
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: "hamelsmu/repo2docker-test"

         